name: yazi
base: core22
version: git
summary: Blazing fast terminal file manager
description: |
    Yazi, which means "duck", is a terminal file manager written in Rust, based on non-blocking async I/O.
    It aims to provide an efficient, user-friendly, and customizable file management experience.
license: MIT

grade: stable
confinement: classic

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: amd64
    build-for: arm64

apps:
  yazi:
    command: yazi
    # plugs: [ home, removable-media ]

parts:
  yazi:
    plugin: rust
    source: .
    override-build: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source "$HOME/.cargo/env"
      cargo build --release
      ls -lh
      #cargo install fd-find --root /usr
      #cargo install ripgrep --root /usr
      #cargo install zoxide --root /usr
      git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
      ~/.fzf/install --bin
      ls -lh
    # build-packages:
    #  - git
    #override-stage: |
    #  cargo install fd-find --root 
    #  cargo install ripgrep --root 
    #  cargo install zoxide --root 
    #  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    #  ~/.fzf/install --bin
    #  mv yazi usr/bin

  test:
    after: [ yazi ]
    plugin: nil
    override-build: ''
    override-stage: ''
    override-prime: |
      ls -lh
      ls -lh usr/bin
