name: yazi
base: core22
version: git
summary: Blazing fast terminal file manager
description: |
    Yazi, which means "duck", is a terminal file manager written in Rust, based on non-blocking async I/O.
    It aims to provide an efficient, user-friendly, and customizable file management experience.
license: MIT

grade: stable
confinement: classic

architectures:
  - build-on: amd64
    build-for: amd64
  #- build-on: amd64
  #  build-for: arm64

apps:
  yazi:
    command: yazi
    # plugs: [ home, removable-media ]

parts:
  yazi:
    plugin: rust
    source: .
    override-build: |
      craftctl default
      ls -alh $CRAFT_PART_INSTALL
      #cargo install fd-find --root $CRAFT_PART_INSTALL
      #cargo install ripgrep --root $CRAFT_PART_INSTALL
      #cargo install zoxide --root $CRAFT_PART_INSTALL
      cargo install fd-find
      cargo install ripgrep
      cargo install zoxide
      ls -alh
      ls -alh /
      ls -alh /usr/bin
      git clone --depth 1 https://github.com/junegunn/fzf.git fzf
      fzf/install --bin
      #mv fzf/bin/ $CRAFT_PART_INSTALL
    override-stage: |
      craftctl default
      ls -alh
    override-prime: |
      craftctl default
      ls -alh
