name: yazi
base: core22
version: git
summary: Blazing fast terminal file manager
description: |
    Yazi, which means "duck", is a terminal file manager written in Rust, based on non-blocking async I/O.
    It aims to provide an efficient, user-friendly, and customizable file management experience.
license: MIT

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: amd64
    build-for: arm64

apps:
  yazi:
    command: target/release/yazi
    plugs: [ home, removable-media ]

parts:
  yazi:
    plugin: rust
    source: .
    #override-build: |
    #  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    #  source "$HOME/.cargo/env"
    #  cargo build --release
    stage-packages:
      - fd-find
      - ripgrep
      - zoxide
  
   test:
     plugin: nil
     override-build: |
     	ls $SNAP/stage
     	ls $SNAP/prime
