name: snap

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build-snap-package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - uses: snapcore/action-build@v1
      - uses: actions/upload-artifact@v4
        with:
          name: snap
          # path: ${{ steps.snapcraft.outputs.snap }}
          path: yazi*.snap
          retention-days: 1
