name: Build Snap Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-snap-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: snapcore/action-build@v1
      - uses: actions/upload-artifact@v4
        with:
          name: snap
          path: yazi*.snap
          retention-days: 1
